# version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeperx
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - EasyEats-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - EasyEats-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5003:5003"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=5003
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=your_super_secret_key
      - JWT_EXPIRES_IN=1h
      - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_users?retryWrites=true&w=majority
    networks:
      - EasyEats-network
    restart: on-failure

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    ports:
      - "3002:3002"
    environment:
      - JWT_SECRET=your_super_secret_key
      - JWT_EXPIRES_IN=1h
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_users?retryWrites=true&w=majority
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - EasyEats-network
    restart: on-failure

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_users?retryWrites=true&w=majority
      - KAFKA_BROKER=kafka:9092
    networks:
      - EasyEats-network
    restart: on-failure

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5002:5002"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_orders?retryWrites=true&w=majority
      - KAFKA_BROKER=kafka:9092
    networks:
      - EasyEats-network
    restart: on-failure

  resturant-service:
    build: ./resturant-service
    container_name: resturant-service
    ports:
      - "5004:5004"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=5004
      - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_resturants?retryWrites=true&w=majority
      - KAFKA_BROKER=kafka:9092
      - CLOUDINARY_CLOUD_NAME=denqj4zdy
      - CLOUDINARY_API_KEY=931338397364491
      - CLOUDINARY_API_SECRET=MPyY4EXbYpPs7c9_6VC-O16Qm_Q
    networks:
      - EasyEats-network
    restart: on-failure

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "5005:5005"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - PORT=5005
      - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_notifications?retryWrites=true&w=majority
      - KAFKA_BROKER=kafka:9092
      - EMAIL_USER=radalapuththu@gmail.com
      - EMAIL_PASSWORD=lltaxfluinkzxbxs
      - TWILIO_ACCOUNT_SID=AC4bae37c77902e4e82bd53da5f8fed20d
      - TWILIO_AUTH_TOKEN=bba99268c95c5d2915dada3cc32053d7
      - TWILIO_PHONE_NUMBER=+15868003046
    networks:
      - EasyEats-network
    restart: on-failure

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5006:5006"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
    - PORT=5006
    - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_payments?retryWrites=true&w=majority
    - STRIPE_SECRET_KEY=sk_test_51RGkbGP1kuLOW6vWPbqAzPhgdsXeMRLulgMeYVDRHVw8SmOzsc6ePOokXhCwEhtJuONLR0h6NNnG5bSB4TvXvteo00B8CKnJdg
    - STRIPE_WEBHOOK_SECRET=whsec_rN53tA2CKB1pb3ZkMW3QNI39A1KDNlQb
    - KAFKA_BROKER=kafka:9092  # Changed from localhost:9092
    networks:
      - EasyEats-network
    restart: on-failure

  location_org:
    build: ./location_org
    container_name: location_org
    ports:
      - "3001:3001"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
    - PORT=3001
    - CLIENT_URL=http://localhost:5173
    - NODE_ENV=development
    - MONGO_URI=mongodb+srv://madhawaawishka:madhawaawishka@cluster0.ixf1ahz.mongodb.net/EasyEatsDB_delivery?retryWrites=true&w=majority
    - KAFKA_BROKER=kafka:9092  # Added this line
    networks:
      - EasyEats-network
    restart: on-failure

networks:
  EasyEats-network:
    driver: bridge